import { amazonSearch, vendorUrl } from "./affiliates.ts";
import {
  ALL_LEVELS,
  PRICE_SOURCE,
  type Product,
} from "./types.ts";

function item(
  partial: Omit<Product, "currency" | "priceSource" | "sportTags"> & {
    sportTags?: string[];
    currency?: Product["currency"];
    priceSource?: string;
  },
): Product {
  return {
    sportTags: ["basketball"],
    currency: "USD",
    priceSource: PRICE_SOURCE,
    ...partial,
  };
}

/**
 * US high-school / youth / AAU basketball catalog.
 * Hardware links are live amazon.com product or search URLs.
 * Software links are live vendor pages (paste referral URLs once you are approved).
 */
export const catalog: Product[] = [
  item({
    id: "teamsnap-season",
    name: "TeamSnap (season)",
    category: "software",
    levelTags: ALL_LEVELS,
    covers: ["registration"],
    priceEstimate: 199,
    affiliateUrl: vendorUrl("https://www.teamsnap.com/"),
    vendor: "TeamSnap",
    notes: "Roster, schedule, and parent payments. Default US youth / school team app.",
    group: "registration",
  }),
  item({
    id: "band-team",
    name: "Band app (team)",
    category: "software",
    levelTags: ["youth", "high_school"],
    covers: ["registration"],
    priceEstimate: 0,
    affiliateUrl: vendorUrl("https://band.us/"),
    vendor: "BAND",
    notes: "Free team board. Fits a small rec side that does not need billing.",
    group: "team-comms",
    maxRoster: 18,
  }),
  item({
    id: "sportsengine",
    name: "SportsEngine (season)",
    category: "software",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["registration"],
    priceEstimate: 349,
    affiliateUrl: vendorUrl("https://www.sportsengine.com/"),
    vendor: "SportsEngine",
    notes: "Heavier registration + website stack used by many US clubs and schools.",
    group: "registration",
    minRoster: 22,
    minBudget: 1500,
  }),
  item({
    id: "hudl-assist",
    name: "Hudl Assist (season)",
    category: "software",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["film"],
    priceEstimate: 800,
    affiliateUrl: vendorUrl("https://www.hudl.com/products/assist"),
    vendor: "Hudl",
    notes: "Breakdown + tagging. Only when film is a weekly staff workflow.",
    group: "film-software",
    minBudget: 1800,
  }),
  item({
    id: "hudl-board",
    name: "Hudl (team plan)",
    category: "software",
    levelTags: ALL_LEVELS,
    covers: ["film"],
    priceEstimate: 120,
    affiliateUrl: vendorUrl("https://www.hudl.com/"),
    vendor: "Hudl",
    notes: "Clip library without Assist. Mid-budget film path.",
    group: "film-software",
    minBudget: 500,
    maxBudget: 1799,
  }),
  item({
    id: "veo-club-software",
    name: "Veo Club recording plan",
    category: "software",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["film"],
    priceEstimate: 540,
    affiliateUrl: vendorUrl("https://www.veo.co/"),
    vendor: "Veo",
    notes: "Cloud recording that pairs with Veo Cam. Do not buy without the camera.",
    group: "film-software",
    minBudget: 2500,
  }),
  item({
    id: "maxpreps-schedule",
    name: "MaxPreps team page",
    category: "software",
    levelTags: ["high_school"],
    covers: ["travel"],
    priceEstimate: 0,
    affiliateUrl: vendorUrl("https://www.maxpreps.com/"),
    vendor: "MaxPreps",
    notes: "Free high-school schedule and scores. Travel planning stays in a shared sheet.",
    group: "travel-software",
  }),
  item({
    id: "teamsnap-events",
    name: "TeamSnap events / travel",
    category: "software",
    levelTags: ["youth", "club", "college_club"],
    covers: ["travel"],
    priceEstimate: 49,
    affiliateUrl: vendorUrl("https://www.teamsnap.com/"),
    vendor: "TeamSnap",
    notes: "Away-day events and carpools inside the team app.",
    group: "travel-software",
    maxBudget: 400,
  }),
  item({
    id: "gofundme",
    name: "GoFundMe campaign",
    category: "software",
    levelTags: ALL_LEVELS,
    covers: ["fundraising"],
    priceEstimate: 29,
    affiliateUrl: vendorUrl("https://www.gofundme.com/"),
    vendor: "GoFundMe",
    notes: "One-off parent / booster raise. Platform takes a fee; this is the operational cost estimate.",
    group: "fundraising",
  }),
  item({
    id: "booster-fundraising",
    name: "Booster (season)",
    category: "software",
    levelTags: ["youth", "high_school", "club"],
    covers: ["fundraising"],
    priceEstimate: 99,
    affiliateUrl: vendorUrl("https://www.booster.com/"),
    vendor: "Booster",
    notes: "School / team merchandise fundraiser. Use when you need more than one GoFundMe.",
    group: "fundraising",
    minBudget: 700,
  }),

  item({
    id: "phone-tripod",
    name: "JOBY GripTight PRO 2 phone tripod",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["film"],
    priceEstimate: 29,
    affiliateUrl: amazonSearch("JOBY GripTight PRO 2 GorillaPod phone tripod"),
    vendor: "Joby",
    notes: "A flexible phone mount for baseline or bleacher filming when a dedicated camera does not fit the budget.",
    group: "film-capture",
    maxBudget: 599,
  }),
  item({
    id: "gopro-hero",
    name: "GoPro HERO (bundle)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["film"],
    priceEstimate: 249,
    affiliateUrl: amazonSearch("GoPro HERO Black bundle"),
    vendor: "GoPro",
    notes: "Fence or baseline capture for games and practice. Mid-budget film kit.",
    group: "film-capture",
    minBudget: 600,
    maxBudget: 2499,
  }),
  item({
    id: "veo-cam",
    name: "Veo Cam 3",
    category: "hardware",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["film"],
    priceEstimate: 2690,
    affiliateUrl: vendorUrl("https://www.veo.co/veo-cam"),
    vendor: "Veo",
    notes: "Automatic pan-tilt game camera. Only when film is weekly and the budget is large.",
    group: "film-capture",
    minBudget: 2500,
    minRoster: 12,
  }),
  item({
    id: "marker-cones-50",
    name: "SKLZ Shot Spotz court markers",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 32,
    affiliateUrl: amazonSearch("SKLZ Shot Spotz basketball court markers"),
    vendor: "SKLZ",
    notes: "Numbered floor targets for youth spacing, footwork, and shooting stations without a pile of generic cones.",
    group: "practice-layout",
  }),
  item({
    id: "disc-markers-40",
    name: "Brother P-touch equipment labeler",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["travel"],
    priceEstimate: 35,
    affiliateUrl: amazonSearch("Brother P-touch PTD220 label maker bundle"),
    vendor: "Brother",
    notes: "Labels cameras, chargers, ball bags, med supplies, and travel bins so shared equipment comes back.",
    group: "equipment-labeling",
  }),
  item({
    id: "training-bibs-14",
    name: "GoSports numbered scrimmage vests (12)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 32,
    affiliateUrl: amazonSearch("GoSports numbered scrimmage vests 12 pack"),
    vendor: "GoSports",
    notes: "Two colors for even-sided games. One set covers a 15-player practice.",
    group: "training-bibs",
  }),
  item({
    id: "agility-poles-12",
    name: "Agility poles (set)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["s_and_c"],
    priceEstimate: 45,
    affiliateUrl: amazonSearch("agility poles basketball training 12 pack"),
    vendor: "SKLZ",
    notes: "Closeout and ball-screen gates. Useful once you run a separate skill block.",
    group: "agility",
  }),
  item({
    id: "youth-balls-8",
    name: "Youth indoor balls (4)",
    category: "hardware",
    levelTags: ["youth"],
    covers: [],
    priceEstimate: 88,
    affiliateUrl: amazonSearch("Wilson Evolution basketball size 27.5 youth"),
    vendor: "Wilson",
    notes: "Size 27.5 / 28.5 for rec and middle school. Four balls covers station work.",
    group: "match-balls",
    maxRoster: 20,
  }),
  item({
    id: "club-balls-12",
    name: "Wilson Evolution (4-pack)",
    category: "hardware",
    levelTags: ["high_school", "club", "college_club"],
    covers: [],
    priceEstimate: 300,
    affiliateUrl: amazonSearch("Wilson Evolution basketball 29.5 indoor"),
    vendor: "Wilson",
    notes: "Size 29.5 indoor game/practice balls. Four Evolutions is the usual varsity baseline — not a 12-pack.",
    group: "match-balls",
    minRoster: 12,
  }),
  item({
    id: "popup-goals",
    name: "SKLZ Kick-Out shot return",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 45,
    affiliateUrl: amazonSearch("SKLZ Kick-Out basketball shot return"),
    vendor: "SKLZ",
    notes: "A hoop-mounted return chute that keeps a short shooting station moving without assigning a rebounder.",
    group: "shooting-efficiency",
  }),
  item({
    id: "ball-bag-pump",
    name: "Baden ball bag + dual-action pump",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 32,
    affiliateUrl: amazonSearch("Baden basketball ball bag dual action pump"),
    vendor: "Baden",
    notes: "One carry bag plus a manual pump keeps the shared ball set together and at playable pressure.",
    group: "ball-care",
  }),
  item({
    id: "tactics-board",
    name: "Fox 40 SmartCoach Pro basketball clipboard",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 24,
    affiliateUrl: amazonSearch("Fox 40 SmartCoach Pro basketball clipboard"),
    vendor: "Fox 40",
    notes: "A double-sided full-court / half-court dry-erase board. One for the head coach, not one per assistant.",
    group: "tactics",
  }),
  item({
    id: "pitch-medkit",
    name: "Sideline first-aid kit",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["medkit"],
    priceEstimate: 42,
    affiliateUrl: amazonSearch("sports first aid kit athletic trainer bag"),
    vendor: "Ever Ready",
    notes: "Tape, gauze, gloves, cold packs. Operational only — not a medical protocol.",
    group: "medkit",
  }),
  item({
    id: "first-aid-backpack",
    name: "Athletic trainer backpack",
    category: "hardware",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["medkit"],
    priceEstimate: 78,
    affiliateUrl: amazonSearch("athletic trainer first aid backpack"),
    vendor: "Line2Design",
    notes: "Larger kit for 18+ player squads with Friday doubles. Still not a diagnosis tool.",
    group: "medkit",
    minRoster: 18,
    minBudget: 1200,
  }),
  item({
    id: "ice-pack-set",
    name: "Instant ice packs (12)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["medkit"],
    priceEstimate: 16,
    affiliateUrl: amazonSearch("instant ice packs 12 pack sports"),
    vendor: "Amazon",
    notes: "Disposable cold packs to restock the kit. Not injury advice.",
    group: "med-ice",
  }),
  item({
    id: "polar-h10",
    name: "Polar H10 strap (coach unit)",
    category: "hardware",
    levelTags: ["high_school", "club", "college_club"],
    covers: ["s_and_c"],
    priceEstimate: 89,
    affiliateUrl: amazonSearch("Polar H10 heart rate monitor chest strap"),
    vendor: "Polar",
    notes: "One coach/demo strap, not a 15-player GPS fleet.",
    group: "s_and_c-hr",
    minBudget: 900,
  }),
  item({
    id: "resistance-bands",
    name: "Resistance band set",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["s_and_c"],
    priceEstimate: 22,
    affiliateUrl: amazonSearch("Fit Simplify resistance loop bands set"),
    vendor: "Fit Simplify",
    notes: "Warm-up and posterior-chain work without a weight room.",
    group: "s_and_c-bands",
  }),
  item({
    id: "speed-ladder",
    name: "Speed ladder + mini hurdles",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["s_and_c"],
    priceEstimate: 35,
    affiliateUrl: amazonSearch("agility ladder and mini hurdles basketball"),
    vendor: "SKLZ",
    notes: "Footwork station. Useful when weekly hours include a separate S&C block.",
    group: "s_and_c-footwork",
  }),
  item({
    id: "water-carrier",
    name: "Team water cooler (3 gal)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 38,
    affiliateUrl: amazonSearch("Igloo 3 gallon sports water cooler"),
    vendor: "Igloo",
    notes: "Shared water for a 90-minute practice. More relevant as weekly hours climb.",
    group: "hydration",
  }),
  item({
    id: "rebounder-net",
    name: "SKLZ D-Man defensive mannequin",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 120,
    affiliateUrl: amazonSearch("SKLZ D-Man basketball defensive mannequin"),
    vendor: "SKLZ",
    notes: "A repeatable closeout and finishing obstacle for high-rep skill stations. Skip on a tight budget.",
    group: "extra-rebound",
    minBudget: 800,
  }),
  item({
    id: "kit-duffels",
    name: "Team duffels (pair)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["travel"],
    priceEstimate: 64,
    affiliateUrl: amazonSearch("Nike Brasilia team duffel bag large 2 pack"),
    vendor: "Nike",
    notes: "Away-day bags. One for balls/pinnies, one for med + admin.",
    group: "travel-kit",
  }),
  item({
    id: "corner-flags",
    name: "Court boundary markers",
    category: "hardware",
    levelTags: ["club", "youth"],
    covers: [],
    priceEstimate: 22,
    affiliateUrl: amazonSearch("basketball court boundary markers outdoor"),
    vendor: "Champion Sports",
    notes: "Only for outdoor rec courts that are not lined.",
    group: "field-flags",
  }),
  item({
    id: "foam-rollers",
    name: "Foam rollers (4)",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: ["s_and_c"],
    priceEstimate: 48,
    affiliateUrl: amazonSearch("foam roller 18 inch 4 pack athletic"),
    vendor: "Amazon",
    notes: "Shared recovery tools. Not a treatment plan.",
    group: "s_and_c-recovery",
    minBudget: 700,
  }),
  item({
    id: "whistle-stopwatch",
    name: "Fox 40 Sonik Blast whistle + stopwatch",
    category: "hardware",
    levelTags: ALL_LEVELS,
    covers: [],
    priceEstimate: 18,
    affiliateUrl: amazonSearch("Fox 40 Sonik Blast whistle stopwatch set"),
    vendor: "Fox 40",
    notes: "Staff pocket kit. Cheap, always useful.",
    group: "coach-pocket",
  }),

  item({
    id: "usa-basketball-youth",
    name: "USA Basketball youth coach license",
    category: "education",
    levelTags: ["youth", "club"],
    covers: [],
    priceEstimate: 45,
    affiliateUrl: vendorUrl("https://www.usab.com/"),
    vendor: "USA Basketball",
    notes: "Standard rec/AAU license path. One for the staff, not the roster.",
    group: "education",
  }),
  item({
    id: "nfhs-rules",
    name: "NFHS basketball rules (book)",
    category: "education",
    levelTags: ["high_school"],
    covers: [],
    priceEstimate: 12,
    affiliateUrl: amazonSearch("NFHS basketball rules book"),
    vendor: "NFHS",
    notes: "High-school rules. One copy for the staff.",
    group: "education",
    maxBudget: 799,
  }),
  item({
    id: "coaching-manual",
    name: "Coaching Basketball Successfully (book)",
    category: "education",
    levelTags: ["high_school", "club", "college_club"],
    covers: [],
    priceEstimate: 28,
    affiliateUrl: amazonSearch("Coaching Basketball Successfully Morgan Wootten"),
    vendor: "Human Kinetics",
    notes: "Staff read. One copy is enough.",
    group: "education",
    minBudget: 800,
  }),
];

export const catalogById: Record<string, Product> = Object.fromEntries(
  catalog.map((p) => [p.id, p]),
);

export function getProduct(id: string): Product | undefined {
  return catalogById[id];
}

